version: 1.1.0.{build}
branches:
  only:
  - master
environment:
  TestVariables:
    secure: SNbiIrjKaGL3EUurLoHYHIw67MDCQWaTHTQBWR3Gi9sMf6hIW+rinrcxnhohpfmDdPKrzFYBKiWg5ne1VNxThC8EcxwL/zH5kU4UdoqhAC9WsxjGrAQJdCeQLEf/nb4UJDuC7P0iWELzhaRZGK+CE3iBq6j8TE0+j/+0Nm/Kwox97pjj19SBps8VURDuUSBXv6NkTcKvyMYts1D1Io79BzC8qiPH89PC01J+uZuigAV61x+5JdMfzcH5hsXYq2IyOzmeGs/NGiW43ZdhvU6CjoAGfLFAkPZDh2pyBtKGlj3Os1/Zi2EbFthBnnLNUHjK7pd4wCCC9f2cgsAL6mLnXU3dquX7iAKREjd7+wF9xTB5KR+u/Af7LuaTxrS2DBu6
  gh_token:
    secure: Zp+1OaziEY3qRLb2m0fodp+pmezszMM4aE5ZcXcWJgMcAOa5gxjdVNWKT5Ve3xt4
  psg_token:
    secure: g/oJpBtSPY2iV9FeothbxDMD+j11wA7ZHLrHLcd54mKhRzyEOcABk2+BKA1pU8ul
skip_branch_with_pr: true
skip_tags: true
init:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
install:
  - ps: Install-Module -Name Psake, Pester, PSScriptAnalyzer, PlatyPS, BuildHelpers, GitHubReleaseManager -Force
build_script:
  - ps: .\build.ps1
