version: 2.0.0.{build}
branches:
  only:
  - master
  - development
environment:
  TestVariables:
    secure: sD7DCYu5R1vjytOawpbD7lOfhk4WKAX/QfZb9AR1j8iYs/1XjylpVMdaAtHHKcJDYhNAEztk47N/taoOqhcrOwr118IWKV5Yxbf+bw01c8v0xd5nR2DovxT/8eZ1Nc2IZBKFiheTX2M7JCAifPjHWE/u99Dp8dpBSJAmRK1lwKYIpQ+DIfwXZQbaWJeeE/RYOGjj9bZQ2+wxWGmQAO0tOXglSyOQ75Z43kf6y1XYCmztx/yhUMhbAxJbFhbrttlyG+wmPYv6IB4QNNYcpPk37+3Z1suOvN/eOLOPGWGnKdik9J1RDUL/4YWNh9fKxfP5
  gh_token:
    secure: Zp+1OaziEY3qRLb2m0fodp+pmezszMM4aE5ZcXcWJgMcAOa5gxjdVNWKT5Ve3xt4
  psg_token:
    secure: g/oJpBtSPY2iV9FeothbxDMD+j11wA7ZHLrHLcd54mKhRzyEOcABk2+BKA1pU8ul
skip_branch_with_pr: true
skip_tags: true
init:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
install:
  - ps: Install-Module -Name Psake, Pester, PSScriptAnalyzer, PlatyPS, BuildHelpers, GitHubReleaseManager -Force
build_script:
  - ps: .\build.ps1
