version: 1.0.0.{build}
branches:
  only:
  - master
image: WMF 5
build: off
init:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
install:
  - ps: Install-Module -Name Psake, Pester, PSScriptAnalyzer, PlatyPS -Force
test_script:
  - ps: .\build.ps1 -Task Analyze