name: '$(Major).$(Minor).$(Patch)-$(Rev:r)'
pool:
  vmImage: 'windows-latest'

resources:
- repo: self
  clean: true

steps:
- task: PowerShell@1
  displayName: 'Execute Build'
  inputs:
    scriptName: tools/build.ps1

- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST_*.xml'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**\TEST_*.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: Release'
  inputs:
    SourceFolder: tools

    Contents: |
     New-GitHubRelease.ps1
     Publish-PSModule.ps1

    TargetFolder: Release

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Release'
  inputs:
    PathtoPublish: Release
    ArtifactName: Release