---

site_name: OneTimeSecret
repo_url: https://github.com/chelnak/OneTimeSecret
site_author: Chelnak
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "OneTimeSecret is licenced under the <a href='https://github.com/chelnak/OneTimeSecret/raw/master/LICENSE'>MIT license"
pages:
- 'Home' : 'index.md'
- 'Change log' : 'CHANGELOG.md'
- 'Functions':
    - Get-OTSAuthorizationToken : functions/Get-OTSAuthorizationToken.md
    - Get-OTSRecentMetadata : functions/Get-OTSRecentMetadata.md
    - Get-OTSSecret : functions/Get-OTSSecret.md
    - Get-OTSSecretMetadata : functions/Get-OTSSecretMetadata.md
    - Get-OTSSystemStatus : functions/Get-OTSSystemStatus.md
    - New-OTSSecret : functions/New-OTSSecret.md
    - New-OTSSharedSecret : functions/New-OTSSharedSecret.md
    - Remove-OTSSecret : functions/Remove-OTSSecret.md
    - Set-OTSAuthorizationToken : functions/Set-OTSAuthorizationToken.md
